name: Java CI Exercie 2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Compile Java code
        run: javac "TP1/Exercice 2/src/Verbe.java" "TP1/Exercice 2/src/MyClass.java" "TP1/Exercice 2/src/Result.java"

      - name: Run Java program
        run: echo -e "CHANTER" | java -cp "TP1/Exercice 2/src" MyClass
